- hosts: all
  become: yes
  become_user: root
  roles:
    - role: common
    - role: langs
    - role: web-bootstrap
    - role: web-go
    - role: web-node
    - role: web-rust
    - role: web-deno
    - role: web-prepare
    - role: remove
