name: release

on:
  push:
    tags:
      - v*.*.*
    branches-ignore:
      - '**'

env:
  IMAGE_NAME: isucon10-qualify

jobs:
  make-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.1
      - run: npm ci
        working-directory: ./webapp/frontend
      - run: npm run build
        working-directory: ./webapp/frontend
      - run: npm run export
        working-directory: ./webapp/frontend
      - name: Archive dist/
        run: tar -zcvf ./out.tar.gz ./out
        working-directory: ./webapp/frontend
      - name: Create Release and upload out.tar.gz
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./webapp/frontend/out.tar.gz